---
services:
  inkfra:
    build:
      context: .
    image: ddosian/inkfra:latest
    environment:
      CHECK_INTERVAL: "10"
      DEBUG_OUTPUT: "True"
    volumes:
      - ./config:/config:ro
      - ./output:/output:rw
    restart: unless-stopped
  nginx:
    image: nginx:latest
    volumes:
      - ./output:/usr/share/nginx/html:ro
    ports:
      - 80:80
    restart: unless-stopped
